### ISSUE TITLE
Defining egress policy without domain should not be allowed

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#1035]
**Describe the bug:** (a clear and concise description of what the bug is)

**To Reproduce**

1. Define service with network policy as follows:

```
teamConfig:
    demo:
        services:
            - name: service-a
              networkPolicy:
                  egressPublic:
                      - domain: domain1.com
                        ports:
                            - number: 8443
                              protocol: TCP
```
1. Run `otomi template` 
1. Observe that templating is broken

**Expected behavior:** (a clear and concise description of what you expected to happen)
A domian is a required property
