### ISSUE TITLE
Installation to minikube does not complete

### ISSUE THREAD

**Issue by leiarenee** [redkubes/otomi-core#1044]
When following the instructions within quickstart using minikube, installation job is terminated within metrics server step. It gives certification error. 

Solution advice from Maurice:
```

command:
- /metrics-server
- --kubelet-insecure-tls
- --kubelet-preferred-address-types=InternalIP
```

so the way to override that in otomi is this config snippet:

```
apps:
  metrics-server:
    enabled: true
    _rawValues:
      extraArgs:
        kubelet-preferred-address-types: InternalIP
        kubelet-insecure-tls: true
```
