### ISSUE TITLE
Feature request to add annotations to service definition of the ingress controller

### ISSUE THREAD

**Issue by MichaelTrip** [redkubes/otomi-core#1064]
**Is your feature request related to a problem? Please describe.** 

When deploying on Hetzner, the Service manifest that is created for the Ingress NGINX gets a internal ip, a ipv6 IP and a External IPv4 IP from the LoadBalancer object. This could work ofcourse. But when using External DNS the DNS records are not created because External DNS doesn´t know what to do with the IPv6 address. After a while the deployment fails because External DNS couldn´t create a dns record.

To overcome this problem, you can add some specific annotations to the service manifest:

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    dummy: "true"
    load-balancer.hetzner.cloud/disable-private-ingress: "true"
    load-balancer.hetzner.cloud/ipv6-disabled: "true"
    ....
```
But, this is not possible in the `values.yml` yet.

**Describe the solution you'd like** 

Add the possibility to the Helm `values.yml` to add annotations to the service manifest.

**Describe alternatives you've considered** 
-
**Additional context** 
-
