### ISSUE TITLE
Upgrade external-dns

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#1123]
**Is your feature request related to a problem? Please describe.** 

From:
```
chart version: 6.8.1
app version: 0.11.0  
```
To:
```
chart version: 6.20.3
app version: 0.13.4
```

See: https://artifacthub.io/packages/helm/bitnami/external-dns

**Describe the solution you'd like** A clear and concise description of what you want to happen.

**Describe alternatives you've considered** A clear and concise description of any alternative solutions or features
you've considered.

**Additional context** Add any other context or screenshots about the feature request here.

**Comment by Ani1357** [comment]
Updated external-dns helm chart
Deployed a vanilla k8s cluster on  DO
Installed otomi by using the following values.yaml 
```
cluster:
  k8sVersion: '1.24'
  name: 'dev'
  provider: 'digitalocean'
  domainSuffix: 'dev.aks.redkubes.net'
otomi:
  hasExternalDNS: true
  adminPassword: 'welcomeotomi'
dns:
  provider:
    azure:
      resourceGroup: external-dns
      aadClientId: 66fd<< REDACTED >>ad94
      aadClientSecret: << REDACTED >>
      tenantId: 57a3<< REDACTED >>f695
      subscriptionId: 50c2<< REDACTED >>a5eb
  domainFilters:
    - aks.redkubes.net
apps:
  cert-manager:
    issuer: letsencrypt
    stage: staging
    email: sre@redkubes.net
```
Created a new service in otomi and verified its FQDN is working
Updated otomi-core to the externat-dns-update branch image
Created more services in otomi: the dns records are correctly created in Azure Dns.
Created PR[#1178](https://github.com/redkubes/otomi-core/pull/1178)
