### ISSUE TITLE
Allow using wildcard certificate

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#1134]
# Description

# Story

**AS AN** otomi admin
**I WANT TO** use wildcard certificates
**SO** I do not have to rely on Letsencrypt 

# Acceptance criteria

**GIVEN** a wild card certificate given from organisation 
**WHEN** I set the wild card certificate in Otomi 
**THEN** this certificate is used by all public core and team apps

**GIVEN** I do not have a wild card certificate from my organisation 
**WHEN** I choose lets encrypt as certificate provided 
**THEN** letsencrypt generates wildcard certificate that is used by all core and team apps

**GIVEN** wildcard support
**WHEN** I upgrade Otomi to new version
**THEN** wildcard certificate is used instead certificate per app

**GIVEN** there are multilevel domain names in Otomi
**WHEN** I support wildcard certificate
**THEN** all core and team apps are on the same domain level

By the same domain level we mean
```
grafana.<clusterDomainSuffix>
grafana-team-a.<clusterDomainSuffix>
mysvc-team-a.<clusterDomainSuffix>
```
instead of 
```
grafana.<clusterDomainSuffix>
grafana.team-a.<clusterDomainSuffix>
mysvc.team-a.<clusterDomainSuffix>
```

# Definition of done

- [x] Relevant PRs are merged
- [x] Tested by peer
- [x] Updated documentation reviewed by peer
- [x] Short demo video recorded and stored on google drive (if applicable)

**Comment by j-zimnowoda** [comment]
```
apps:
    cert-manager:
        useWildcardCert: true|false
```
If `useWildcardCert` is set to true then only `otomi-wildcard` Certificate is going to be issued and shared among all hosts. Example:
```
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: otomi-wildcard
spec:
  secretName: otomi-wildcard-crt
  issuerRef: 
    kind: Issuer
    name: letsencrypt-prod
  commonName: "*.{{$clusterDomainSuffix}}"
  dnsNames:
    - "*.{{$clusterDomainSuffix}}"
```


Alternatively a user may opt out from issuing the wildcard cert by cert-manager and bring its own trusted wildcard cert
```
apps:
    cert-manager:
        byoWildcardCert: <cert>

```
Then Otomi should deploy `otomi-wildcard-crt` secret to the `istio-system` namespace.
