### ISSUE TITLE
Upgrade Loki ( 2.8.2)  and promtail (2.8.2)

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#1135]
Loki
```yaml
apiVersion: v2
name: loki
description: Helm chart for Grafana Loki in simple, scalable mode
type: application
appVersion: 2.8.2
version: 5.5.12
home: https://grafana.github.io/helm-charts
```

Promtail
```yaml
apiVersion: v2
name: promtail
description: Promtail is an agent which ships the contents of local logs to a Loki instance
type: application
appVersion: 2.8.2
version: 6.11.2
home: https://grafana.com/loki
```
