### ISSUE TITLE
Upgrade Kured (1.13.0)

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#1136]
```
apiVersion: v1
appVersion: 1.13.0
description: A Helm chart for kured
home: https://github.com/kubereboot/kured
icon: https://raw.githubusercontent.com/kubereboot/website/main/static/img/kured.png
maintainers:
- email: christian.kotzbauer@gmail.com
  name: ckotzbauer
- email: david@davidkarlsen.com
  name: davidkarlsen
name: kured
sources:
- https://github.com/kubereboot/kured
version: 4.5.0
```
