### ISSUE TITLE
harbor-registry-htpasswd regenerated at each commit

### ISSUE THREAD

**Issue by srodenhuis** [redkubes/otomi-core#1230]
At each build (Drone), the `harbor-registry-htpasswd` secret is re-created and results in harbor-registry being re-deployed.

**To Reproduce**
Steps to reproduce the behaviour:

1. Enable Harbor
2. Create a build (or any other resource)
3. Check the Drone pipeline

**Expected behaviour:

Harbor registry not being re-deployed at each build

**Screenshots:**

```
# Source: harbor/templates/registry/registry-secret.yaml
  apiVersion: v1
  kind: Secret
  metadata:
    labels:
      app: harbor
      chart: harbor
      heritage: Helm
      release: harbor
    name: harbor-registry-htpasswd
  data:
-   REGISTRY_HTPASSWD: '-------- # (66 bytes)'
+   REGISTRY_HTPASSWD: '++++++++ # (66 bytes)'
  type: Opaque
---
harbor, harbor-registry, Deployment (apps) has changed:
  # Source: harbor/templates/registry/registry-dpl.yaml
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: "harbor-registry"
    labels:
      heritage: Helm
      release: harbor
      chart: harbor
      app: "harbor"
      component: registry
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    strategy:
      type: Recreate
      rollingUpdate: null
    selector:
      matchLabels:
        release: harbor
        app: "harbor"
        component: registry
    template:
      metadata:
        labels:
          heritage: Helm
          release: harbor
          chart: harbor
          app: "harbor"
          component: registry
        annotations:
          checksum/configmap: 50286eeadbf67602d451d5f2fffdc7b561a471affcc3cc26ef1315b82546fa43
-         checksum/secret: f5d7ca20386f7b8abbdbe64dfdd3f251e167699c772608472f381cc31b48b91a
+         checksum/secret: c4e90118399ab44b2f28bfe4d851753681f13cf763d3f5c101344f63eab98542
```

**Versions:**

- Core Version: 0.24.1

**Comment by j-zimnowoda** [comment]
Hi @srodenhuis 
I followed the steps and could not reproduce this error.
Could you provide the values that you are using to deploy Otomi?

**Comment by srodenhuis** [comment]
```
cluster:
  k8sVersion: "1.25"
  name: dev
  provider: scaleway
  domainSuffix: dev.d2-otomi.net
otomi:
  version: my-branch
  hasExternalDNS: true
  adminPassword: xxxxxx
apps:
  cert-manager:
    issuer: letsencrypt
    stage: production
    email: sre@redkubes.net
dns:
  domainFilters: 
    - d2-otomi.net
  provider:
    aws:
      credentials:
        secretKey: xxxxx
        accessKey: xxxx
      region: eu-central-1
```
