### ISSUE TITLE
Install fails on `job-keycloak` in kind/minikube with MetalLB

### ISSUE THREAD

**Issue by ams0** [redkubes/otomi-core#1283]
**Describe the bug:** (a clear and concise description of what the bug is)

Install fails at `job-keycloak` because the user `otomi-admin` is not there:

keycloak logs:
```
keycloak-0 keycloak 2023-09-20 06:52:21,937 WARN  [org.keycloak.events] (executor-thread-4) type=LOGIN_ERROR, realmId=7822f06e-973d-497d-8832-068da1b1e678, clientId=admin-cli, userId=null, ipAddress=10.244.3.109, error=user_not_found, auth_method=openid-connect, grant_type=password, client_auth_method=client-secret, username=otomi-admin
```

job-keycloak logs:
```
job-keycloak-9pvkf job-keycloak Exiting!
job-keycloak-9pvkf job-keycloak OPError: invalid_grant (Invalid user credentials)
job-keycloak-9pvkf job-keycloak     at processResponse (/app/node_modules/openid-client/lib/helpers/process_response.js:38:13)
job-keycloak-9pvkf job-keycloak     at Client.grant (/app/node_modules/openid-client/lib/client.js:1338:22)
job-keycloak-9pvkf job-keycloak     at processTicksAndRejections (node:internal/process/task_queues:94:5)
job-keycloak-9pvkf job-keycloak     at async main (/app/dist/tasks/keycloak/keycloak.js:36:17) {
job-keycloak-9pvkf job-keycloak   error: 'invalid_grant',
job-keycloak-9pvkf job-keycloak   error_description: 'Invalid user credentials'
```

My values:
```
cluster:
  name: "kind-otomi"
  provider: "kind"
otomi:
  adminPassword: <redacted>
  version: 'kc_upgrade'
apps:
  metrics-server:
    enabled: true
    _rawValues:
      extraArgs:
        kubelet-preferred-address-types: InternalIP
        kubelet-insecure-tls: true
```

I'm on otomi-0.5.53, kind 1.25.3

**To Reproduce**

**Expected behavior:** (a clear and concise description of what you expected to happen)

**Screenshots:** (if applicable, add screenshots to help explain your problem)

**Cluster(s):**

- Cloud: [e.g. aws]
- Cluster: [e.g. demo]

**Versions:** (seen in console's `/settings`)

- Core Version [e.g. 0.12.34]
- Console Version: [e.g. aws]
- API version: [e.g. 0.4.56]

**Desktop:** (if relevant)

**Smartphone:** (if relevant)

**Additional context:** (add any other context about the problem here)
