### ISSUE TITLE
Support values migration for teams

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#1435]
**Is your feature request related to a problem? Please describe.**

Sometimes we need to migrate team values by defining migration in `values-changes.yaml` file. However current implementation does not support migration of many objects because it only uses a simple `get` method from loadsh library.

**Describe the solution you'd like**
To apply migration on every object key and every array element:
```
    relocations:
    - teamConfig.{team}.abc: teamConfig.{team}.efg   # For every team relocate abc to efg
    - teamConfig.{team}.services[service]. abc: teamConfig.{team}.services[service]. efg # For every service in every team relocate abc to efg
    additions:
      - teamConfig.{team}.hij: true                                        # For every team add hij
      - teamConfig.{team}.services[service].klm: true    # For every service in every team  add elm
    deletions:
      - teamConfig.{team}.nop.enabled                              # For every team remove enabled
      - teamConfig.{team}.services[service].rst               # For every service in every team
    mutations:
    - teamConfig.{team}.uvw: teamConfig.{team}.xyz # For every team set uvw to xyz
    - teamConfig.{team}.services[service].uvw: teamConfig.{team}.services[service].xyz # For every service in every team  set uvw to xyz
```
