### ISSUE TITLE
Do not allow to define two network policies for the same domain

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#1470]
**Is your feature request related to a problem? Please describe.** 
The following `egressPublic` policy will cause problems during deployment to k8s cluster.
```
              networkPolicy:
                  egressPublic:
                      - domain: example.com
                        ports:
                            - number: 443
                              protocol: HTTPS
                            - number: 80
                              protocol: HTTP
                      - domain: example.com
                        ports:
                            - number: 443
                              protocol: HTTPS
                            - number: 80
                              protocol: HTTP
                  ingressPrivate:
                      mode: AllowAll
```

**Describe the solution you'd like** A clear and concise description of what you want to happen.
Do not allow to define two  policies that are referring to the same domain.
