### ISSUE TITLE
Set Pod dnsConfig for installation job

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#1481]
**Is your feature request related to a problem? Please describe.**

Pods are using DNS provided by the cloud provider.
Unfortunately we observe that cloud provider DNS often does not updates its records frequently. This can take even 30 minutes. It can be very confusing because often happens that users can resolve domains from their own hosts.

**Describe the solution you'd like** A clear and concise description of what you want to happen.

For the following K8s jobs
- [x] wait-for-otomi-realm
- [x] job-keycloak
- [ ] otomi ?

Configure:
```
      dnsConfig:
          nameservers:
            - 8.8.8.8
            - 8.8.4.4
          searches:
            - {{ .Values.cluster.domainSuffix }}
```

**Describe alternatives you've considered** A clear and concise description of any alternative solutions or features
you've considered.

**Additional context** Add any other context or screenshots about the feature request here.
