### ISSUE TITLE
Move network policies out of team service object

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#1493]
# WHY
1. Network policies are about workloads (Pods) not services
2. Egress policies are namespace wide

# User Story

**AS A** team user 
**I WANT TO** access team network policies from the left side menu
**AND** use Pod labels to assign the `ingress Policies`
**SO** I can define them independently from workloads and services
**AND** I can also allow traffic from namespaces that do not belong to any team

# Acceptance criteria

**GIVEN** existing networkPolicy object in each team service
**WHEN** I upgrade Otomi to a new version
**THEN** All the policies are migrated from `<team>.services.[*].networkPolicy` to `<team>.networkPolicies[*]`

**GIVEN** `podSelector` that is applicable only to the ingressPrivate (not to egressPublic)
**WHEN** I upgrade Otomi to a new version
**THEN** `podSelector` is migrated under the `ingressPrivate` property
**AND** renamed to `toLabel`

**GIVEN** `ingressPrivate` property with `team` and `service` properties  
**WHEN** I upgrade Otomi to a new version
**THEN** `team` property is renamed to `fromNamespace` 
**AND** `team` property values prefixed with `team-`
**AND** `service` property is renamed to `fromLabel` 

**GIVEN** `selfService.service.networkPolicy` property within a `team`  
**WHEN** I upgrade Otomi to a new version
**THEN** `networkPolicy` property is moved under `selfService.networkPolicy` 
**AND** otomi-api leverages the new property to establish user permissions

# Definition of done

- [ ] Relevant PRs are merged
- [ ] Tested by peer
- [ ] Updated documentation reviewed by peer
- [ ] Short demo video recorded and stored on google drive (if applicable)

**Comment by j-zimnowoda** [comment]
example:
```
netpol:
   - type: ingressPrivate
      name: my-net
     toNamespace: team-a
     fromNamespace: team-b
     toLabel: 
      - a=b
     fromLabel: 
      - a=b
   - type: ingressPrivate
     name: my-net-2
     toNamespace: team-a
     fromNamespace: team-b
     toLabel: 
      - a=b
     fromLabel: 
      - a=b
    - type: ingressPrivate
      name: toGoogle
      domain: https://google.com
```
