### ISSUE TITLE
Fix template validation issues

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#168]
# Overview
The `otomi validate-templates` reveals several issues that should be fixed

## yaml unmarshal errors
 
- [ ] charts/nginx-ingress/templates/controller-servicemonitor.yaml
Double release label - Kubernetes pickup ignore one and does not complain
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-ingress-controller
  labels:
    app: nginx-ingress
    chart: nginx-ingress-1.40.3
    component: "controller"
    heritage: Helm
    release: nginx-ingress
    release: prometheus-operator
```

- [x] charts/team-ns/templates/istio-virtualservices.yaml
Double rewrite definition for the same route
```
    -
      match:
        - uri:
            prefix: '/servant-1'
      rewrite:
        uri: /
      rewrite:
        authority: servant1.team-otomi.dev.onprem.otomi.cloud
        uri: "/"
``` 
- [x] charts/team-ns/templates/istio-virtualservices.yaml
Double  "autoscaling.knative.dev/minScale" key
```
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '1'
        autoscaling.knative.dev/minScale: "1"
```

## Missing istio CRD
The istio CRDs are created by Istio Operator
```
WARN - team-ns/templates/istio-virtualservices.yaml containing a VirtualService (prometheus-team-dev-dev-onprem-otomi-cloud) was not validated against a schema
```

## Missing schema for CustomValidationDefinition resource
The early canonical k8s schema [repos](https://github.com/instrumenta/kubernetes-json-schema/tree/master/v1.17.0-standalone
) do not provide schema for CustomResourceDefinition, thus some our tool report an errors like:

```
WARN - cert-manager/templates/crds.yaml containing a CustomResourceDefinition (certificates.cert-manager.io) was not validated against a schema
```

```
ERR  - knative-init-0.16/templates/all.yaml: Failed initializing schema file:///tmp/kubernetes-json-schema/master/v1.16.0-standalone/customresourcedefinition-apiextensions-v1beta1.json: open /tmp/kubernetes-json-schema/master/v1.16.0-standalone/customresourcedefinition-apiextensions-v1beta1.json: no such file or directory
```
