### ISSUE TITLE
[design] - As a user I want to access kubernetes cluster by authenticating with custom IdP

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#215]
# User story

As a user I want to access to kubernetes cluster by authenticating with custom IdP, so I can reuse identities and associated policies defined by my organization.

The otomi containers platform promises to be a cloud native solution. Followwing that concept a customer can use its own IdP from a different vendor than the managed cluster where otomi is running. Unfortunately some cloud providers do not allow fpr that. Due to that reason we decided to leverage short-lived Service Account tokens for accessing the kube-api server.

# Accessing kubernetes cluster with otomi containers platform

There are three steps that a user needs to perform in order to access a kubernetes cluster API:

1. A user authenticates with otomi containers platform
1. A user interacts with kubernetes cluster
1. Tokens are refreshed automatically

The next subsection walks through each step and explains it in detail.

## A user authenticates with otomi containers platform

The authentication process can be divided into two steps:

1. Obtain JWT from IdP
2. Exchange JWT for k8s Service Account token

A user calls `otomi login` that performs set of actions that presented in the following sequence diagram:

<img width="969" alt="image" src="https://user-images.githubusercontent.com/17126497/100999642-4c1afd80-355d-11eb-8968-1aee9dec2811.png">

From the diagram: **1-7:** Obtain JWT from keycloak. The JWT is used for authentication before accessing `jwt-to-rbac` service and for creating kubernetes Service Account (SA). **8-14:** Obtain Kubernetes SA token. The jwt-to-rbac parses JWT (id_token.groups), creates short-lived SA and binds a matching Cluster Role. **15-16:** Generate config for kubectl that authenticates with obtained Service Account token **17-18:** Interact with kubernetes cluster API. **19-22:** refresh service account token.

The `otomi kube-config` command takes 3 environment variables: `CLOUD`, `CLUSTER` and `OTOMI_JWT`. The `CLOUD`, `CLUSTER` are mandatory ones and are used for retriving kube-api URL and keycloak URL from values repo. The `OTOMI_JWT` is an optional one. If provided, steps **1-7** are skipped. Note: it may happen that int the meantime the id_token from JWT has also expired, thus refresh_token will be used to refresh JWT.

The `JWT-to-rbac`provides SA token with associated user info

```json
[
  {
    "name": "janedoe-example-com-token-df3re",
    "data": {
      "ca.crt": "example-ca-cer-base64",
      "namespace": "ZGVmYXVsdA==",
      "token": "example-k8s-sa-token-with-ttl-base64"
    }
  }
]
```
## A user interacts with kubernetes cluster

Successful authentication, performed by `otomi kube-config` command, results in configuration file that can be used by kubectl. The file contains information about user, cluster and context. The following snippets presents each item separately.

```yaml
users:
  - name: <jwt.name>-<rand>
    user:
      auth-provider:
        config:
          access-token: <sa-token.data.token>
        name: otomi
```

```yaml
clusters:
  - cluster:
      certificate-authority: <sa-token.data.ca.cert>
      server: '<clusters.yaml#clouds.$CLOUD.clusters.$CLUSTER.apiServer>'
    name: '<settings.yaml#customer.name>-<$CLOUD>-<$CLUSTER>'
```

```yaml
contexts:
  - context:
      cluster: '<settings.yaml#customer.name>-<$CLOUD>-<$CLUSTER>'
      namespace: '<sa-token.data.namespace>'
      user: '<jwt.name>-<rand>'
    name: '<settings.yaml#customer.name>-<$CLOUD>-<$CLUSTER>'
```

## Tokens are refreshed automatically

A short lived Service Account is deleted by its controller after it expires. It means that a new Service Account should be created. The kube config format allows to define actions re-authentication flow, which will levarage `otomi kube-config` command.

Previously presented user configuration can be extended by `cmd-arg`, `cmd-path`, `env` and `expiry` properties.

```yaml
users:
  - name: <jwt.name>-<rand>
    user:
      auth-provider:
        config:
          access-token: <sa-token.data.token>
          cmd-args: kube-config
          cmd-path: $ENV_DIR/bin/otomi
          env:
            - name: CLOUD
              value: google
            - name: CLUSTER
              value: dev
            - name: OTOMI_JWT
              value: <jwt>
            - name: ENV_DIR
              value: <absolute file path to values repo>
          expiry: <time.now + x min>
        name: otomi
```

The `expiry` property instructs kubectl command to call `cmd-path` together with `cmd-args` and `env` after `access-token` expiries.

# References:

- https://github.com/banzaicloud/jwt-to-rbac
- https://banzaicloud.com/blog/kubeconfig-security/
- https://banzaicloud.com/blog/k8s-rbac/
- https://auth0.com/blog/refresh-tokens-what-are-they-and-when-to-use-them/

# Appendix
```
sequenceDiagram
autonumber
    user->>shell: otomi login
    shell->>web-browser: open_url(CLOUD, CLUSTER)
    web-browser->>keycloak: authenticate
    keycloak->>web-browser: auth_code
    web-browser->>shell: auth_code
    shell->>keycloak: get_jwt(auth_code)
    keycloak->>shell: jwt
    shell->>jwt-to-rbac: create_sa(jwt)
    jwt-to-rbac->>kube-api: create Service Account
    kube-api->>jwt-to-rbac: sa
    jwt-to-rbac->>shell: sa
    shell->>jwt-to-rbac: get_sa_token(jwt)
    kube-api->>jwt-to-rbac: sa_token
    jwt-to-rbac->>shell: sa_token
    shell->>shell: generate_context(sa_token, CLOUD, CLUSTER)
    shell->>shell: kubectl use_context
    user->>shell: kubectl <cmd>
    shell->>kube-api: HTTP DELETE/GET/POST/PUT Headers.Authorization: $sa_token
    Note over user,jwt-to-rbac: sa_token expiries
    user->>shell: kubectl <cmd>
    shell->>shell: otomi login
    shell->>keycloak: refresh_token(jwt.refresh_token)
    keycloak->>shell: jwt
    Note over shell,kube-api: repeat steps 8-15
```
### Obtain JWT from keycloak

```bash
The project https://github.com/please-openit/oidc-bash-client provides a convincing script to obtain JWT that can be then used fo testing jwt-to-rbac service.

OIDC_ENDPOINT='https://keycloak.dev.eks.otomi.cloud/realms/master/.well-known/openid-configuration'
OIDC_REDIRECT_URI='http://127.0.0.1:8080'
OIDC_CLIENT_ID='otomi'
OIDC_SCOPE='openid'
OIDC_CLIENT_SECRET=<client secret>

./oidc-client.sh --operation authorization_code_grant --client-id $OIDC_CLIENT_ID --openid-endpoint $OIDC_ENDPOINT --redirect-uri $OIDC_REDIRECT_URI --scope $OIDC_SCOPE

OIDC_AUTHZ_CODE='<code>'
JWT=./oidc-client.sh --operation auth_code --client-id $OIDC_CLIENT_ID --openid-endpoint $OIDC_ENDPOINT --redirect-uri $OIDC_REDIRECT_URI --authorization-code $OIDC_AUTHZ_CODE --client-secret $OIDC_CLIENT_SECRET
```
### Interact with jwt-to-rbac
Parse id_token
ID_TOKEN=$(echo $JWT | jq -r .id_token)

Create a tunnel to jwt-to-rbac service
```
k -n shared port-forward svc/jwt-to-rbac 5555:5555
```

Request a new service account:
```bash
curl --request POST \
 --url http://localhost:5555/rbac/ \
 --header 'Content-Type: application/json' \
 --data '{"token": "$JWT"}'
```

Parse id token
```
sed 's/\./\n/g' <<< $ID_TOKEN | base64 --decode
```

```json
{
  "access_token": "<access_token>",
  "expires_in": 60,
  "refresh_expires_in": 1800,
  "refresh_token": "<refresh_token>",
  "token_type": "bearer",
  "id_token": "<id_token>",
  "not-before-policy": 0,
  "session_state": "3f8b5389-2b5f-4b45-a98f-ac51e8d43a54",
  "scope": "profile email openid"
}
```
