### ISSUE TITLE
otomi-values: errors out of the box

### ISSUE THREAD

**Issue by svatwork** [redkubes/otomi-core#220]
**Describe the bug:** (a clear and concise description of what the bug is)

After setting otomi-values/env/clusters.yaml and otomi-values/env/clouds/aws/dev/* and would like to validate my templates and values, I receive a couple of errors.

**To Reproduce**
1. 

```
mkdir otomi-values && cd $_ && git init .
docker run -e ENV_DIR=$PWD -v $PWD:$PWD otomi/core:latest bin/bootstrap.sh
. bin/aliases
```

2. Set otomi-values/env/clusters.yaml (CLOUD=aws && CLUSTER=dev) and otomi-values/env/clouds/aws/dev/*:

(used '-' to distort the actual values)

clusters.yaml:
```
clouds:
    aws:
        domain: -----
        clusters:
            dev:
                enabled: true
                apiName: arn:aws:eks:------:----------:cluster/------
                apiServer: -----.gr7.-----.eks.amazonaws.com
                k8sVersion: '1.1-'
                otomiVersion: 'master'
                region: ------
```

otomi-values/env/clouds/aws/dev/.env
```
export K8S_CONTEXT="-------------" # equal to ~/.kube/config
```

3. 

Error 1:
```
VERBOSE=1 otomi validate-templates && otomi validate-values
CWD: 0-11-40
bin/otomi: line 355: [: !=: unary operator expected
Info: The 'secrets.*.yaml files' are not decrypted, because /Users/sebastiaanverbeek/Projects/redkubes/test/0-11-40/.sops.yaml file is not present
has_docker=1
ENV_DIR=/Users/sebastiaanverbeek/Projects/redkubes/test/0-11-40
stack_dir=/home/app/stack
helm_config=/Users/sebastiaanverbeek/Library/Preferences/helm
cmd_image=otomi/core:master
check_kube_context=1
K8S_CONTEXT=-----------
IN_DOCKER=
command=bin/validate-templates.sh
Running dockerized version of command: bin/validate-templates.sh
Generating Kubernetes v1.18.0 Manifests for aws-dev.
helmfile-init.yaml: basePath=.
in helmfile.tpl/helmfile-init.yaml: failed to render values files "../values/k8s/k8s-raw.gotmpl": failed to render [../values/k8s/k8s-raw.gotmpl], because of template: stringTemplate:15:34: executing "stringTemplate" at <$team.clusters>: map has no entry for key "clusters"
Validation Failed
```

Error 2:
.vscode/values-schema.yaml:

```
See screenshots; can't copy multiple problems in vscode (#25290). 
```

**Expected behavior:** (a clear and concise description of what you expected to happen)

I expect the first run to go smoothly and without errors. 

**Screenshots:** (if applicable, add screenshots to help explain your problem)

![Screenshot 2020-11-30 at 10.30.12.png](https://images.zenhubusercontent.com/5fb3eb135472cfeda30e7684/91f26d7e-e02c-4a3e-8188-690c5be99cfd)

![Screenshot 2020-11-30 at 10.30.26.png](https://images.zenhubusercontent.com/5fb3eb135472cfeda30e7684/fce27d92-7965-405c-8d4d-5b44e9dc28e5)

**Cluster(s):**
 - Cloud: aws
 - Cluster: dev

**Versions:** (seen in console's `/settings`)
 - Core Version [e.g. 0.11.45?]
 - Console Version: ?
 - API version: ?

**Desktop:** (if relevant)
 - OS: MacOS 
 - Browser: -
 - Version: 10.14.6

**Additional context:** (add any other context about the problem here)
