### ISSUE TITLE
getting credentials: exec: executable aws not found

### ISSUE THREAD

**Issue by svatwork** [redkubes/otomi-core#224]
**Describe the bug:** (a clear and concise description of what the bug is)

My hypothesis is that including MFA in the awscli will require a new executable in the tools and core image.

**To Reproduce**
1. 
kubeconfig

```
kind: Config
preferences: {}
users:
- name: ------
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - eu-central-1
      - eks
      - get-token
      - --cluster-name
      - otomi-eks-dev
      command: /usr/local/bin/aws
      env:
      - name: AWS_PROFILE
        value: 2auth
```

2. 

```
otomi diff
Info: The 'secrets.*.yaml files' are not decrypted, because /Users/sebastiaanverbeek/Projects/redkubes/test/otomi-values/.sops.yaml file is not present
Comparing release=jobs-artifacts, chart=../charts/raw
Comparing release=knative-init, chart=/tmp/charts/knative-init-0.18
Comparing release=loki-artifacts, chart=../charts/raw
Listing releases matching ^gatekeeper-operator$
in helmfile.d/helmfile-03.init.yaml: 4 errors:
err 0: command "/home/app/tools/helm" exited with non-zero status:
PATH:
  /home/app/tools/helm
ARGS:
  0: helm (4 bytes)
  1: diff (4 bytes)
  2: upgrade (7 bytes)
  3: --reset-values (14 bytes)
  4: --allow-unreleased (18 bytes)
  5: loki-artifacts (14 bytes)
  6: ../charts/raw (13 bytes)
  7: --namespace (11 bytes)
  8: monitoring (10 bytes)
  9: --values (8 bytes)
  10: /tmp/values206189261 (20 bytes)
ERROR:
  exit status 1
EXIT STATUS
  1
STDERR:
  WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/app/.kube/config
  WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/app/.kube/config
  Error: Failed to get release loki-artifacts in namespace monitoring: exit status 1: WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/app/.kube/config
```

**Expected behavior:** (a clear and concise description of what you expected to happen)

Exit code 0 and showed me the helmfile diff.

**Screenshots:** (if applicable, add screenshots to help explain your problem)

**Cluster(s):**
 - Cloud: aws
 - Cluster: -----dev

**Versions:** (seen in console's `/settings`)
 - Core Version 0.11.50
 - Console Version: aws
 - API version --

**Additional context:** (add any other context about the problem here)
I will investigate and post results by including it in the Dockerfile, and I'll probably open a pull request soon.
