### ISSUE TITLE
A user can define env name when its value is referenced from a secret

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#323]
**Is your feature request related to a problem? Please describe.**

Having a secret defined like below:
```
kind: Secret
metadata: test
spec:
  data:
    target: xyz
    source: xyz
```

A user can define Knative Service, and instruct to take env value from an existing kubernetes secret.
```
teamConfig:
    teams:
        dev:
            services:
                - name: httpenv
                  ksvc:
                      secrets:
                          - name: test
                            entries:
                                - target
```

After deploying the team-ns chart, the KnativeSevice looks like:
```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: httpenv
spec:
  template:
    spec:
      containers:
          env:
            - name: TARGET
              valueFrom:
                secretKeyRef:
                  name:  test
                  key: target
```

From the above snippet, the env name (`TARGET`) is templated by the otomi based the `target` key from the `test` secret.
Otomi cannot enforce env name, because the application defines its interface. The secret can be shared among many services and each one can expect different env name.

**Describe the solution you'd like** A clear and concise description of what you want to happen.
Add option to define env name in case env value is taken from secret. 

**Describe alternatives you've considered**
n/a
