### ISSUE TITLE
Job ENV variables are shared between init container & running container

### ISSUE THREAD

**Issue by Dunky13** [redkubes/otomi-core#338]
**Describe the bug:** (a clear and concise description of what the bug is)
There is one config map created for both the init container and the running container. When you have the same values in the init as well as running container, it would store the value twice in the config map, making otomi/k8s complain

**To Reproduce**
Create a new Job:
```yaml
{{- $v := .Environment.Values }}
{{- $c := $v.charts }}

type: Job
name: gitea
enabled: true
env:
  GITEA_URL: https://gitea.{{ $v.cluster.domain }}
  GITEA_PASSWORD: {{ $c | get "gitea.admin.password" "bladibla"}}
init:
  env:
    GITEA_URL: https://gitea.{{ $v.cluster.domain }}
    GITEA_PASSWORD: {{ $c | get "gitea.admin.password" "bladibla"}}
  image:
    repository: otomi/tools
    tag: v1.4.13
    pullPolicy: IfNotPresent
  shell: bash
  script: |
    {{- readFile "scripts/init/gitea.sh" | nindent 4 }}
image:
  repository: otomi/tools
  tag: v1.4.13
  pullPolicy: IfNotPresent
shell: bash
script: |
  {{- readFile "scripts/gitea.sh" | nindent 2 }}
runPolicy: Always
```

The config map created would be templated as follows:
```yaml
# Source: jobs/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: job-gitea
  labels:
    helm.sh/chart: jobs-0.1.0
    app.kubernetes.io/name: jobs
    app.kubernetes.io/instance: job-gitea
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
data:
    GITEA_PASSWORD: bladibla
    GITEA_URL: https://gitea.dev.eks.otomi.cloud
    GITEA_PASSWORD: bladibla
    GITEA_URL: https://gitea.dev.eks.otomi.cloud
---
``` 
Where data contains duplicate keys (and values)

**Expected behavior:** (a clear and concise description of what you expected to happen)
Not storing duplicate key/value pairs.

**Versions:** (seen in console's `/settings`)
- Core Version - current master

**Proposed solution:**
Create two config maps, one for the init container, and one for the running container.
Would need to double check that the existing jobs move the ENV variables accordingly.

**Comment by svatwork** [comment]
I like that you re-use our job chart, well done! Also a good catch of this use-case.

In your feature branch, do you think we can split it up like this:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: job-{{ $v.name }}
  labels: {{- include "jobs.labels" $ | nindent 4 }}
data:
  {{- with $v.env }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $v.init.env  }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
```

into

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: job-{{ $v.name }}
  labels: {{- include "jobs.labels" $ | nindent 4 }}
data:
  {{- with $v.env }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: job-{{ $v.name }}
  labels: {{- include "jobs.labels" $ | nindent 4 }}
data:
  {{- with $v.init.env  }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
```
