### ISSUE TITLE
update otomi with workaround for docker run in linux

### ISSUE THREAD

**Issue by Morriz** [redkubes/otomi-core#353]
See last comments

**Comment by Dunky13** [comment]
Will research this on my linux machine to see if this is an issue or a non-issue

**Comment by svatwork** [comment]
I bake my own container image and don't use the `app` user, works fine now.

**Comment by Morriz** [comment]
Can you provide more details for others here to help them?

**Comment by svatwork** [comment]
For development purposes:

1. Remove the following from the tools Docker:

```
RUN chown -R app:app /home/app
USER app
```

2. Docker build the tools image, e.g.

```bash
 docker build -t otomi/tools:my-tools -e NPM_TOKEN=$NPM_TOKEN . 
```

3. Replace the `otomi-core` Dockerfile's referred image to the built tools image:

```
FROM otomi/tools:my-tools as test
FROM otomi/tools:my-tools as prod
```

4. Replace every occurrence of `--chown=app` from the root Dockerfile's source code:

```bash
COPY --chown=app . .
```

with 

```bash
COPY . .
```

5. Build the `otomi-core` image, e.g.

```bash
docker build -t otomi/core:my-core .
``` 

6. Replace `otomiVersion` in `otomi-values` with core image, e.g.:

```yaml
clouds:
    aws:
        domain: eks.otomi.cloud
        clusters:
            dev:
                enabled: true
                apiName: eks_otomi-cloud_eu-central-1_otomi-eks-dev
                apiServer: BFE1BC8655F2C73189DCE38F5E40D0AC.gr7.eu-central-1.eks.amazonaws.com
                k8sVersion: '1.19'
                otomiVersion: my-core
```
