### ISSUE TITLE
vault install problems

### ISSUE THREAD

**Issue by Morriz** [redkubes/otomi-core#357]
**Describe the bug:** (a clear and concise description of what the bug is)

Two issues observed:

- helmfile 03 and 05 are probably too close so a race condition occurs and 05 can't find the crds from 03
- after deploying again another error occurs:
```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Vault.spec.vaultPodSpec): unknown field "resources" in com.banzaicloud.vault.v1alpha1.Vault.spec.vaultPodSpec
```

**To Reproduce**

1. Install `-l pkg=vault` on a fresh cluster
2. Oberve above issues

**Comment by j-zimnowoda** [comment]
O wow, 

Shall I implement 'prepare' hook that will wait until CRD is available? E.g.:

helmfile.d/helmfile-05.init.yaml:
```
  - name: vault-operator-artifacts
    installed: {{ $c | get "vault.enabled" true }}
    namespace: vault
    labels:
      pkg: vault
    hooks:
      - events: ["prepare"]
        showlogs: true
        command: "../bin/wait-for-crd.sh"
        args: ["vault.banzaicloud.com"]
    <<: *raw
```

bin/wait-for-crd.sh:
```
# In loop check if CRD exists
k api-resources | grep  $1
```
