### ISSUE TITLE
Remove CLOUD and CLUSTER dependencies

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#384]
- [x] remove `*overrides*.yaml` files 
- [x] remove `clouds/$CLUSTER` structures and consolidate team files like so:
```
teams/jobs.*.yaml
teams/secrets.*.yaml
teams/services.*.yaml
```
- [x] Rework loading of environment in `helmfile.d/snippets/defaults.gotmpl` and `helmfile.d/snippets/env.gotmpl` accordingly
- [x] Add `cluster` object to values that describes single cluster and is currently is derived according to CLOUD and CLUSTER  environment 
```
cluster:
  apiName: eks_otomi-cloud_eu-central-1_otomi-eks-demo
  apiServer: 5B31672F99FF867B3CB4D8E0831B6FE7.gr7.eu-central-1.eks.amazonaws.com
  domain: demo.eks.otomi.cloud
  enabled: true
  k8sVersion: '1.19'
  name: demo
  otomiVersion: v0.12.8
  provider: aws
  region: eu-central-1
```
- [x] Simplify `clouds structure`, e.g.:

```
clouds:
  aws:
    domain: eks.otomi.cloud
    clusters:
      demo:
        enabled: false
```

- [x] Move `env/clusters/$CLOUD/.env` to `.env`
- [ ] Add `export KUBECONFIG=${ENV_DIR:-$PWD}/secrets.kubeconfig.yaml.dec` to .env
- [x] Remove CLOUD and CLUSTER environment variables 
- [x] Remove `--cluster` `--all` CLI parameters
- [x] bootstrap values for a specific cloud provider `otomi bootstrap  <aws|azure|google|onprem>`
- [ ] refactor DNS settings
