### ISSUE TITLE
Nodes require a reboot on azure demo cluster (+others ?)

### ISSUE THREAD

**Issue by bartusz01** [redkubes/otomi-core#411]
**Describe the bug:** (a clear and concise description of what the bug is)
AKS automatically checks for OS security fixes or kernel updates on the Linux nodes and installs them on a nightly basis.  Some of these fixes/updates require a node reboot. In this case, a file `/var/run/reboot-required` will be automatically created on the host. AKS does not automatically restart the nodes! 

I'm not sure about this scenario for AWS/Google. For on-premise we are using [Kured](https://github.com/weaveworks/kured). Perhaps we can look into using this on our (Azure) clusters as well. 

**To Reproduce**

1.  deploy the following manifest on the cluster:

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: check-reboot
  namespace: default
  labels:
    app: check-reboot
spec:
  selector:
    matchLabels:
      name: check-reboot
  template:
    metadata:
      labels:
        name: check-reboot
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
        - name: check-reboot
          image: busybox
          imagePullPolicy: Always
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          command: [ "sh", "-c"]
          args:
          - while true; do
              [ -f /host/reboot/reboot-required ] && echo "check-reboot status - $MY_NODE_NAME reboot required" || echo "check-reboot status - $MY_NODE_NAME no action required";
              sleep 100;
            done;
          resources:
            requests:
              cpu: 5m
              memory: 50Mi
          volumeMounts:
            - name: host-reboot
              mountPath: /host/reboot
              readOnly: true
      volumes:
      - name: host-reboot
        hostPath:
          path: /var/run/
          type: Directory
```

2. Check the logs (`kubectl logs -l name=check-reboot --tail 1`)

**Expected behavior:** (a clear and concise description of what you expected to happen)
Expecting all logs to contain "no action required" i.e. the nodes to be restarted when `/var/run/reboot-required` exists
