### ISSUE TITLE
make schema more robust

### ISSUE THREAD

**Issue by Morriz** [redkubes/otomi-core#414]
The schema now does not check wether certain properties come together. We have to modify the schema to group those together using `anyOf` blocks. Example:

```yaml
azure:
  properties:
    monitor:
      properties:
        clientId: ...
        clientSecret: ...
```

should become

```yaml
azure:
  properties:
    monitor:
      properties:
        anyOf:
          - properties:
              clientId: ...
              clientSecret: ...
            required:
              - clientId
              - clientSecret
```
