### ISSUE TITLE
The otomi validate values failure on kntaive service creation

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#560]
**Describe the bug:**

**To Reproduce**

1. Go to otomi-console and create kntaive service for a team (see additional context)
2. Click on Deploy button
3. Observe that Drone pipeline fails on `tests` stage
See: https://drone.demo.aks.otomi.cloud/otomi/values/6/1/4

**Expected behavior:** 
Deployment of knative succeeds

**Cluster(s):**

- Cloud: azure
- Cluster: demo

**Additional context:**
```
2021-08-30T20:53:21.962Z otomi:validate-templates:warn WARN:  team-ns/templates/knative-services.yaml contains an invalid Service (my-nginx)
234	2021-08-30T20:53:21.962Z otomi:validate-templates:error Templating FAILED
235	2021-08-30T20:53:21.965Z otomi:global:error Error: ENOENT: no such file or directory, unlink '/tmp/otomi/test.yaml'
236	    at unlinkSync (node:fs:1708:3)
237	    at cleanup (file:///home/app/stack/dist/cmd/test.js:17:5)
238	    at file:///home/app/stack/dist/cmd/test.js:21:30
239	    at process.<anonymous> (file:///home/app/stack/dist/common/setup.js:121:9)
240	    at process.emit (node:events:406:35)
241	    at process.exit (node:internal/process/per_thread:184:15)
242	    at validateTemplates (file:///home/app/stack/dist/cmd/validate-templates.js:140:17)
243	    at processTicksAndRejections (node:internal/process/task_queues:96:5)
244	    at async test (file:///home/app/stack/dist/cmd/test.js:25:5)
245	    at async Object.handler (file:///home/app/stack/dist/cmd/test.js:53:9)
```
```
teamConfig:
    teams:
        gogo:
            services:
                -
                    name: my-nginx
                    port: 80
                    id: 680171cc-11e6-44b7-8fc0-6fc6fdd03007
                    ksvc:
                        image:
                            tag: stable
                            pullPolicy: IfNotPresent
                            repository: nginx
                        securityContext:
                            runAsUser: 1001
                            runAsGroup: 1001
                            runAsNonRoot: true
                        resources:
                            limits:
                                cpu: 50m
                                memory: 64Mi
                            requests:
                                cpu: 50m
                                memory: 64Mi
                        scaleToZero: false
                        containerPort: 80
                        autoCD: {}
                        annotations: {}
                        env: {}
                        files: {}
                        secretMounts: {}
                    ownHost: true
                    type: public
```
