### ISSUE TITLE
A service by default is not exposed to the public domain.

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#68]
# EXAMPLE
Add isExposed field:
```
teamConfig:
  teams:
    otomi:
      name: otomi
      services:
        - name: hello
          isPublic: false # does not need oauth2 sso
          isExposed: false # Service is not going to be exposed
          domain: custom.doma.in
          hasCert: true 
        - name: hello2
          isPublic: false # does not need oauth2 sso
          isExposed: true # service is going to be exposed 
          domain: custom.doma.in
          hasCert: true 
```

Adding this feature involves changes in the following files:
- make conditional adding service to Nginx-ingress in`charts/team-ns/templates/nginx-ingress.yaml`
- make conditional adding hosts field for VirtualService in
`charts/team-ns/templates/istio-virtualservices.yaml`
- make conditional adding host to `ingressgateway` in `charts/team-ns/templates/istio-gateway.yaml`

Moreover customer values migration will be needed for already exposed services!

Need to talk to @Morriz about above changes.
