### ISSUE TITLE
Unable to template values with production certificates

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#704]
**Describe the bug:** (a clear and concise description of what the bug is)

**To Reproduce**

Bootstrap with Input values:
```
cluster:
  owner: test
  k8sVersion: '1.20'
  name: quickstart
  provider: azure
  domainSuffix: example.local
otomi:
  hasExternalDNS: true
  version: master
dns:
  provider:
    azure:
      resourceGroup: external-dns
      aadClientId: <redacted>
      aadClientSecret: <redacted>
      tenantId: <redacted>
      subscriptionId: <redacted>
charts:
  cert-manager:
    email: <redacted>
    issuer: letsencrypt
    stage: production
  external-dns:
    domainFilters:
      - <redacted>
```

Observe error:
```
in helmfile.d/helmfile-03.init.yaml: failed to render values files "../values/keycloak/keycloak-raw.gotmpl": failed to render [../values/keycloak/keycloak-raw.gotmpl], because of template: stringTemplate:7:31: executing "stringTemplate" at <.Values._derived.caCert>: map has no entry for key "caCert" +0ms
  otomi:global:error Error: in helmfile.d/helmfile-03.init.yaml: failed to render values files "../values/keycloak/keycloak-raw.gotmpl": failed to render [../values/keycloak/keycloak-raw.gotmpl], because of template: stringTemplate:7:31: executing "stringTemplate" at <.Values._derived.caCert>: map has no entry for key "caCert"
```

**Expected behavior:** (a clear and concise description of what you expected to happen)
While using production certificates Values._derived.caCert shall not be rendered.

**Screenshots:** (if applicable, add screenshots to help explain your problem)

**Cluster(s):**

- Cloud: [e.g. aws]
- Cluster: [e.g. demo]

**Versions:** (seen in console's `/settings`)

- Core Version [e.g. 0.12.34]
- Console Version: [e.g. aws]
- API version: [e.g. 0.4.56]

**Desktop:** (if relevant)

**Smartphone:** (if relevant)

**Additional context:** (add any other context about the problem here)
