### ISSUE TITLE
Install fails on AKS on gitea

### ISSUE THREAD

**Issue by ams0** [redkubes/otomi-core#725]
**Describe the bug:** (a clear and concise description of what the bug is)

Following the [helm installation guide](https://otomi.io/docs/installation/chart) fails on AKS 1.21.7 because `gitea` helm installation gets stuck.

**To Reproduce**

1.Deploy AKS
2.Install otomi with helm
3.Watch it stuck for hours on gitea

**Expected behavior:** (a clear and concise description of what you expected to happen)

Installs goes to the end fine

**Screenshots:** (if applicable, add screenshots to help explain your problem)

**Cluster(s):**

- Cloud: azure
- Cluster: aks 1.21.7

**Versions:** (seen in console's `/settings`)

- Core Version [e.g. 0.12.34]
- Console Version: [e.g. aws]
- API version: [e.g. 0.4.56]

**Desktop:** (if relevant)

**Smartphone:** (if relevant)

**Additional context:** (add any other context about the problem here)

Error:

```
COMBINED OUTPUT:
  Release "gitea" does not exist. Installing it now.
  Error: release gitea failed, and has been uninstalled due to atomic being set: timed out waiting for the condition
    at hfCore (/home/app/stack/dist/src/common/hf.js:46:30)
    exit code: 1
    at ChildProcess.<anonymous> (/home/app/stack/node_modules/zx/dist/bundle.cjs:15343:22)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
```

`./helmfile347885374/gitea-gitea-values-5bff956bfb`

```
nameOverride: gitea
fullnameOverride: gitea

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 128Mi

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false
  readOnlyRootFilesystem: true
  runAsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000

image:
  tag: 1.15.8
  pullPolicy: IfNotPresent
  rootless: true

gitea:
  podAnnotations:
    policy.otomi.io/ignore.init: psp-allowed-users
    policy.otomi.io/ignore.init-ca-finish: psp-allowed-users
  admin:
    username: otomi-admin
    password: uxvxlN28xWtgLfcJ1yBt
  config:
    log:
      LEVEL: trace
    openid:
      ENABLE_OPENID_SIGNIN: true
      ENABLE_OPENID_SIGNUP: true
    repository:
      DEFAULT_BRANCH: main
    service:
      ALLOW_ONLY_EXTERNAL_REGISTRATION: true
    server:
      DOMAIN: gitea.20.23.62.204.nip.io
      ROOT_URL: "https://gitea.20.23.62.204.nip.io/"
      DISABLE_SSH: true


  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        prometheus: system
  oauth:
    - name: otomi-idp
      provider: openidConnect
      key: otomi
      secret: bx7GOxYnICqthhwt3Th9GGBAxhzR7o2Q
      autoDiscoverUrl: https://keycloak.20.23.62.204.nip.io/realms/otomi/.well-known/openid-configuration

init:
  resources:
    limits:
      cpu: 400m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

memcached:
  # @TODO:
  image:
    tag: 1.6.12
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

persistence:
  size: 1Gi

postgresql:
  # @TODO:
  image:
    tag: 13.5.0
  metrics:
    image:
      tag: 0.10.0
  persistence:
    size: 1Gi
  global:
    postgresql:
      postgresqlPassword: 8BFrvPTJMgQ7a3i0WL5U
      postgresqlPostgresPassword: 8BFrvPTJMgQ7a3i0WL5U
  resources:
    limits:
      memory: 512Mi
      cpu: 500m
    requests:
      memory: 256Mi
      cpu: 250m
extraVolumeMounts:
  - name: custom-ca
    mountPath: /etc/ssl/certs/ca-certificates.crt
    subPath: ca-certificates.crt
extraVolumes:
  - name: custom-ca
    secret:
      secretName: custom-ca

podSecurityContext:
  fsGroup: 1000

containerSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
```
