### ISSUE TITLE
The customRootCA and customRootCAKey are always generated regardless cert-managert issuer

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#780]
**Describe the bug:** (a clear and concise description of what the bug is)

**To Reproduce**

1. Deploy otomi with values
```
apps:
    cert-manager:
        email: admins@redkubes.com
        issuer: letsencrypt
        stage: production
```
2. Perform otomi bootstrap
3. Observer that certificates are generated at `env/apps/secrets.cert-manager.yaml` file

**Expected behavior:** (a clear and concise description of what you expected to happen)
The `otomi bootstrap` command does not generate certificate if `issuer: letsencrypt` and `stage: production` are set.
**Screenshots:** (if applicable, add screenshots to help explain your problem)

**Cluster(s):**

- Cloud: [e.g. aws]
- Cluster: [e.g. demo]

**Versions:** (seen in console's `/settings`)

- Core Version [e.g. 0.12.34]
- Console Version: [e.g. aws]
- API version: [e.g. 0.4.56]

**Desktop:** (if relevant)

**Smartphone:** (if relevant)

**Additional context:** (add any other context about the problem here)
