### ISSUE TITLE
alerting setup issues

### ISSUE THREAD

**Issue by bartusz01** [redkubes/otomi-core#797]
**Describe the bug:** (a clear and concise description of what the bug is)
Tried setting up alertmanager to send some alerts to opsgenie together with @staticvoid255. However, we ran into the following issues:

1) Communication between Alertmanager and Prometheus within a team-namespace is not possible if Otomi ingress networkpolicies are deployed. We deployed these netpols as temporary fix:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: temp-fix-prometheus-to-alertmanager
  namespace: team-X
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: team-X
      podSelector:
        matchLabels:
          prometheus: X-po-prometheus 
  podSelector:
    matchLabels:
      alertmanager: X-po-alertmanager
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: temp-fix-alertmanager-to-prometheus
  namespace: team-X
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: team-X
      podSelector:
        matchLabels:
          alertmanager: X-po-alertmanager
  podSelector:
    matchLabels:
      prometheus: X-po-prometheus 
  policyTypes:
  - Ingress
 ```

2) Communication between Kube-state-metrics and Prometheus within a team-namespace is not possible if Otomi ingress networkpolicies are deployed. (deployed a similar networkpolicy to the one above)

3) a team's Prometheus should contain a `probeNamespaceSelector` like below, so it wont allow teams to check all namespaces.
```yaml
probeNamespaceSelector
    matchLabels:                                                                                                                                                                                                        
        name: team-X 
```
4) Teams are able to view alerts from other namespaces. This can be fixed by setting `defaultRules.appNamespacesTarget` to the team's namespace (in prometheus-operator values).

5) ~~We noticed that when setting Opsgenie api-key and url in Otomi UI, these values were not stored in gitea and `selfService` values are duplicated now, see here the redacted content of the `values/env/teams.yaml`:~~
**edit:** Will move this issue to the right repo, not otomi-core.
```yaml
    teamX:
        oidc:
            groupMapping: xxx
        alerts:
            receivers:
                - opsgenie
        resourceQuota:
            pods: '100'
        networkPolicy:
            egressPublic: false
            ingressPrivate: true
        selfService:
            service:                                 
                - ingress
                - networkPolicy
            team:
                - alerts
            Service:                               
                - ingress
            Team:
                - alerts
            apps: []
        id: teamX
```

6) Alertmanager is not updated with new opsgenie configuration. Its config-reloader container does not seem to update `alertmanager-teamx-po-alertmanager-generated` secret while the `alertmanager-teamx-po-alertmanager` secret is updated. ~~(not sure yet why).~~
**edit:** found the issue, opsgenie_configs[].tags is expecting a string (csv), not an array, will create a PR with fixes. 


Otomi core version: v0.16.3
Otomi api version: 0.5.5
Otomi console version: 0.5.9
K8S version: 1.21.2
