### ISSUE TITLE
Gitea never triggers pipelines in Drone

### ISSUE THREAD

**Issue by tre7roja** [redkubes/otomi-core#838]
**Describe the bug:** (a clear and concise description of what the bug is)
`Deploy Changes` never trigger `Drone Pipeline`
Unable to install any apps
The pipeline list is empty in Drone UI

**To Reproduce**

1. Go to 'Apps'
2. Activate an 'app'
3. Click on 'Deploy changes'
4. No error on otomi UI
5. See errors on the drone pods
```
{"commit":"4755b344c9a62a5debd2deebadb67963dccf3d37","event":"custom","level":"info","msg":"trigger: skipping pipeline, does not match event","pipeline":"default","ref":"refs/heads/main","repo":"otomi/values","time":"2022-07-17T22:05:21Z"} 
{"commit":"4755b344c9a62a5debd2deebadb67963dccf3d37","event":"custom","level":"info","msg":"trigger: skipping build, no matching pipelines","pipeline":"default","ref":"refs/heads/main","repo":"otomi/values","time":"2022-07-17T22:05:21Z"}
```

**Expected behavior:** (a clear and concise description of what you expected to happen)
App activated

**Cluster(s):**
- Cluster: [
    custom
    v1.23.8+k3s2
      ```
      "INSTALL_K3S_EXEC='--disable traefik --flannel-backend=none --disable-network-policy --disable servicelb'"
      ```
   quay.io/metallb/controller:v0.13.3
  ]

**Versions:** (seen in console's `/settings`)
Otomi version: v0.16.10
docker.io/otomi/api:v0.5.11 
docker.io/otomi/console:v0.5.15

**Desktop:** (if relevant)

- OS: Windows 10
- Browser [
    Chrome Version 103.0.5060.114 (Build officiel) (64 bits), 
    Firefox102.0.1 (64 bits
  ]

**Additional context:** (add any other context about the problem here)
otomi config
```
cluster:
  k8sVersion: "1.23"
  name: dev
  provider: custom
  domainSuffix: 192.168.0.211.nip.io
otomi:
  adminPassword: '********'
apps:
  host-mods:
    enabled: false
```
metallb 
install
```
kubectl apply -n metallb-system -f https://raw.githubusercontent.com/metallb/metallb/v0.13.3/config/manifests/metallb-native.yaml
```
config
```
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system 
spec:
  addresses:
  - 192.168.0.211-192.168.0.220
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: first-pool-l2advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - first-pool
```

Calico default Install
```
kubectl apply -f https://projectcalico.docs.tigera.io/manifests/calico.yaml
```
 
 Thanks for your project.

**Comment by diabhey** [comment]
Hi @tre7roja : Thanks for reporting. Can you confirm that you indeed followed the [post-install steps](https://github.com/redkubes/quickstart/tree/main/post-install) to activate Drone?

**Comment by tre7roja** [comment]
Hi @diabhey, thanks for your time.
To confirm I reinstall everything and I follow your post-install steps (cert+activation)
During the activation I was redirect to gitea to authorize drone, then I activate the repository in drone.
I try to activate an app and nothing start (no pods).
I searched for logs in drone pod (nothing) and in gitea pod and I found that:
```
2022/07/18 22:13:21 ...s/webhook/deliver.go:259:DeliverHooks() [E] deliver: Post "https://drone.192.168.0.211.nip.io/hook?secret=*********************": dial tcp 192.168.0.211:443: webhook can only call allowed HTTP servers (check your webhook.ALLOWED_HOST_LIST setting), deny 'drone.192.168.0.211.nip.io(192.168.0.211:443)'
```
I'm searching ...

**Comment by tre7roja** [comment]
I changed manually the `app.ini` file in the `gitea` container by adding:
```
[webhook]
ALLOWED_HOST_LIST = *
```
I reboot the container
Then I relaunch the webhook via Gitea UI 
It's working

Thanks to:
https://nixing.mx/posts/configure-gitea-webhooks.html

**Comment by tre7roja** [comment]
Ad hoc workaround
```
suffix=`kubectl get secrets -n default otomi-values -o jsonpath='{.data.values\.yaml}'| base64 -d | yq e '.cluster.domainSuffix'`
kubectl patch secret gitea-inline-config -n gitea --patch-file=/dev/stdin <<-EOF
apiVersion: v1
kind: Secret
type: Opaque
data:
  webhook: `echo -n "ALLOWED_HOST_LIST=drone.$suffix" | base64 -w0`
EOF
```

**Comment by diabhey** [comment]
@staticvoid255/ @j-zimnowoda : Can you check this out? Thanks!

**Comment by tre7roja** [comment]
```
I looked into to a gitea helm chart at charts/gitea but it does not seem to use the webhook property.
Could you describe the issue that you are trying to fix? Cheers
```
@j-zimnowoda 
Hi, Thanks for your reply.
I noticed after a clean install, that the "Deploy Changes" on otomi dashboard doesn't launch nothing.
For example during the "activations steps" this procedure doesn't work:
https://otomi.io/docs/installation/activation/#optional-add-the-url-of-the-kubernetes-api
If I'm not wrong this step launch Gitea webhook and Drone build, but nothing happens.
I found the solution of this problem later in your documentation (Switch to DNS) https://otomi.io/docs/installation/switch-to-dns#step-7-adjust-the-web-hook-in-gitea.
I reinstall the solution many times to validate it.
The workaround above allow to launch webhook correctly after a fresh install.

**Comment by j-zimnowoda** [comment]
Hi @tre7roja 
I have investigated the issue again and here are my findings:


- Otomi uses Gitea in 1.15.8 version. 
- Since  1.15.7 the ALLOWED_HOST_LIST is set to `external`. (Read more: https://docs.gitea.io/en-us/config-cheat-sheet/#webhook-webhook)
- The mentioned issue occurs, because the Loadbalancer IP (192.168.0.X) belongs to a private network and does not match with the condition of `external`

It is environment specific issues, I would like to recommend another solution:
Otomi allows to overwrite a given chart values by means of using `_rawValues`

When you deploy otomi with helm chart add the following spec to the values:
```
apps:
  gitea:
    _rawValues:
      gitea:
        config:
          webhook:
            ALLOWED_HOST_LIST: private
```

The value of ALLOWED_HOST_LIST can be also a specific IP address or domain name, or '*' but in this case I would simply go for `private` which is predefined network in Gitea.

Let me know if you are satisfied with proposed solution.
