### ISSUE TITLE
HPA config for Nginx platform controller and default backend conflicting with RollingUpdate

### ISSUE THREAD

**Issue by staticvoid255** [redkubes/otomi-core#855]
For both the platform controller and default backend deployments the default replica count is 1, whereas the upgrade strategy is as follows:
``` 
replicas: 1
...
strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
```

What myself and @j-zimnowoda  witnessed is that as an update is initiated, new pods are created in an attempt to do the rolling update, but are instantly terminated, likely due to the HPA scaling it down but I am researching this.

From below:
possible solution is to set a maxUnavailable of 50% and maxSurge of 100% to allow the RollingUpdate to override the HPA during the update, which would support situations in which the HPA specifies 1 replica.

In the longer term we can implement validation that will prevent such configs being applied to the cluster.
