### ISSUE TITLE
Kubeclarity deployment fils while gatekeeper validation is enabled

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#856]
**Describe the bug:**

Kubeclarity deployment fils while gatekeeper validation is enabled
**To Reproduce**

With the following configuration it is not possible to deploy kubeclarity

```
apps:
  gatekeeper:
    enabled: true
    disableValidatingWebhook: false
  kubeclarity:
    enabled: true
```

1. Run otomi check-policies  and observe errors:
```

```
4. The security policies will prevent 
```
FAIL - /tmp/otomi/conftest/helmfile-50.services-319d2741-kubeclarity/kubeclarity/templates/deployment.yaml - bannedimagetags - Policy: banned-image-tags - container <kubeclarity-wait-for-sbom-db> didn't specify an image tag <yauritux/busybox-curl>
```
**Expected behavior:** (a clear and concise description of what you expected to happen)
core apps does not fire policy validation errors
