### ISSUE TITLE
Otomi bootstrap git repo with undefined password 

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#926]
**Describe the bug:** (a clear and concise description of what the bug is)

**To Reproduce**

1. Start installation of otomi from chart with the following values
```
cluster:
  domainSuffix: tst-3267319885.aks.otomi.net
dns:
  domainFilters:
    - aks.otomi.net
  provider:
    azure:
      resourceGroup: external-dns
      aadClientId: <redacted>
      aadClientSecret: <redacted>
      tenantId: <redacted>
      subscriptionId: <redacted>
otomi:
  hasExternalDNS: true
``` 

2. Login to the pod performing deployment job
3. go to `env` dir where git repo is initialised and execute  `git remote -v`
4. Observe that the output contains `undefined` password
```
https://otomi-admin:undefined@gitea.tst-3267319885.aks.otomi.net/otomi/values.git
```
