### ISSUE TITLE
[Helm Deployment] Otomi External DNS with GCP not working as expected

### ISSUE THREAD

**Issue by MichaelTrip** [redkubes/otomi-core#934]
[Helm Deployment] Otomi External DNS with GCP not working as expected

**Describe the bug:** (a clear and concise description of what the bug is)

When i try to deploy Otomi on GCP with the external DNS part enabled, the deployment fails. I have these relevant settings configured in the values.yaml:
```yaml
dns:
  provider:
    google:
      serviceAccountKey: "credentials.json"
      project: "michaeltcloud"
```
the  `credentials.json` is the file containing the service account information and should be created as a secret. But it is not being created and the installation fails.

When i, however, create the namespace `external-dns` manually and create a secret containing the `credentials.json`, the dns records are being created in GCP:

```yaml
dns:
  provider:
    google:
      serviceAccountKey: "credentials.json"
      project: "michaeltcloud"
      serviceAccountSecret: "credentials"
      serviceAccountSecretKey: "credentials.json"
```
The setting `serviceAccountKey` is mandatory but not neccesary as i point to the manually created secret. 

But, even with the DNS records being created, the installation fails:

```
ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: release oauth2-proxy-redis failed, and has been uninstalled due to atomic being set: timed out waiting for the condition

COMBINED OUTPUT:
  Release "oauth2-proxy-redis" does not exist. Installing it now.
  Error: release oauth2-proxy-redis failed, and has been uninstalled due to atomic being set: timed out waiting for the condition
    at hfCore (/home/app/stack/dist/src/common/hf.js:44:30)
    exit code: 1
    at ChildProcess.<anonymous> (/home/app/stack/node_modules/zx/dist/bundle.cjs:15261:22)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
  ```

And the installation starts another installation job. The log files is attached to this issue. 
[logs_otomi.txt](https://github.com/redkubes/otomi-core/files/9927946/logs_otomi.txt)

**To Reproduce**

1. apply values.yml with the helm chart
2. job fails

**Expected behavior:** (a clear and concise description of what you expected to happen)

A working otomi instance and working dns records.

**Cluster(s):**

- Cloud: google
- Cluster: test

**Versions:** (seen in console's `/settings`)

Chart version: `0.5.23`
App Version: `v0.16.18`
