### ISSUE TITLE
RawValues editor does not handle properly the YAML Multiline strings correctly

### ISSUE THREAD

**Issue by j-zimnowoda** [redkubes/otomi-core#938]
**Describe the bug:** (a clear and concise description of what the bug is)

This issue occurs while setting values with `Multiline strings` in the `rawValues` editor in otomi console.

The YAML syntax supports two kind of multi line stings
- literal style, indicated by a pipe `|`
- and block Style,  right angle bracket `>`

We observe that the very first `|` from the user input in removed while submitting the form, thus breaking the whole formatting of the YAML file 

**To Reproduce**

1. Go to nginx-ingress app setting and select the rawValues tab
2. Enter the following text and click submit
```
a:
  b: |
    cd

abcd:
  e.yaml: | 
    f.g:
      - i
        j: k
```
3. Refresh the page and observe that formatting is broken:
```
a: b:| cd
abcd:
  e.yaml: |
    f.g:
      - i
        j: k
```

**Expected behavior:** 
rawValues editor supports  YAML Multiline strings
